Update icon size for small buttons
vimeo/iris pull request #141
Opened 2022-06-30 19:51 UTC by brandonhrowe

We recently discovered a minor bug on Safari and Firefox where some icons inside `sm` Buttons are clipped to the bottom and/or right. Some icons that have this happen to them include `Clock`, `Heart`, and `HeartFilled`. This PR:

1. Updates the padding (and thus sizing) value for icons in `sm` Buttons slightly to resolve the issue.
2. Adds a Storybook story to render all Icons within `sm` Buttons to be able to detect which icons face this issue.

<img width="856" alt="Screen Shot 2022-06-29 at 11 15 10 AM" src="https://user-images.githubusercontent.com/46363215/176764267-827e6517-6d89-40d5-9dc7-7a723ca1616e.png">

2022-07-06 01:50 UTC, tylerthegrove requested changes

2022-07-06 13:51 UTC, brandonhrowe commented on src/components/Button/Button.style.ts
> +          overflow: visible;
Added!

2022-07-06 13:51 UTC, brandonhrowe commented on src/components/Button/Button.props.story.tsx
> +            {iconName}
Limited this to the icons from our sidedock, and removed the names inside the buttons.

2022-07-15 15:16 UTC, tylerthegrove approved these changes

2022-07-15 15:17 UTC, merged