Replace color spectrum with react-colorful
vimeo/iris pull request #233
Opened 2023-02-27 13:49 UTC by nathanbrud

## What this PR does
This PR replaces the color spectrum Iris implementation with [react-colorful package](https://omgovich.github.io/react-colorful/).

The current color select is very laggy and buggy.
One of the biggest bugs is that dragging stops when cursor is outside the spectrum so users can't select white / black which is very basic.

## Screenshots & Recordings 

## How it does that
A lot of deleted code from the ColorSpectrum component and replaced with react-colorful.
Some unused props deleted as well from the ColorSelect state.
**No breaking changes at all - all props work the same**

## Testing
Run storybook and see all variants ColorSelect can be used in.

2023-02-28 16:14 UTC, juliewongbandue commented
Hey @nathanbrud, thanks for taking this on. Before we make such a large change, we should definitely add a test here.

2023-02-28 19:15 UTC, nathanbrud commented
@juliewongbandue Sure, added test 💪

2023-03-02 22:00 UTC, juliewongbandue requested changes
Hey Nathan! Thanks for taking this on. A few other packages in our Vimeo repo use some of the props removed in this PR, so to avoid introducing breaking changes in those places, a solution would be to make this a `ColorSelectV2` component.

Since we did not have tests for the original component, it's hard to know if we would be breaking anything. Moving forward, to refactor existing components, we should include tests for the original component first (with 100% coverage) in a separate PR. Then, changes can be made.

I just have some suggestions on the test for _this_ approach to the component though!

cc: @tylerthegrove

2023-03-03 11:02 UTC, nathanbrud commented on src/components/inputs/ColorSelect/ColorSelect.test.tsx
> +    const input = screen.getByTestId('color-select-input');
Sure, changed to use aria-label

2023-03-03 11:02 UTC, nathanbrud commented on src/components/inputs/ColorSelect/ColorSelectInput.tsx
> +        data-testid="color-select-input"
Sure, changed to use aria-label

2023-03-03 11:13 UTC, nathanbrud commented on src/components/inputs/ColorSelect/ColorSelect.test.tsx
> +    fireEvent.click(input);
Change all clicks to `userEvent`

2023-03-03 11:13 UTC, nathanbrud commented on src/components/inputs/ColorSelect/ColorSelect.test.tsx
> +    fireEvent.click(input);
Change all clicks to `userEvent`

2023-03-03 11:32 UTC, nathanbrud commented
Hi @juliewongbandue, I changed the clicks to `userEvent` and removed all `data-testId`.

One of the benefits of using a third party here is that they write most of the tests for us - [as you can see here](https://github.com/omgovich/react-colorful/blob/master/tests/components.test.js)
And we can cover only the delta between the library and our component.

Regarding creating a new v2 component - I can do it if you like but I think we're missing the point here, the current component is very bad - users cannot select black/white in many places across Vimeo because dragging doesn't work when moving the mouse outside the spectrum.
So overriding the current component will fix a critical bug.

Your call :)

2023-03-09 06:30 UTC, closed without merging