Added selected state for Button
vimeo/iris pull request #273
Opened 2023-05-23 07:26 UTC by nathanbrud

## What this PR does 
Adds a checked state for Button that is passed from `<Radio />`

## Screenshots & Recordings 
![image](https://github.com/vimeo/iris/assets/9106375/2b11a6d7-bb09-470e-bd61-d3be50d961fe)

## How it does that 
The `<Radio />` component is passing this prop when cloning the children it gets.

## Testing 
Create a Button and wrap it with Radio, see it gets checked prop based on the Radio toggle

2023-05-23 18:17 UTC, juliewongbandue commented
Hm, I think there is a better way to do this-- button styles could be exported so an element can _look_ like a button, but not exactly _be_ a button. It looks like when clicking on the button directly in your story, the `checked` prop does not get passed since the DOM structure looks something like this: 

```
<input id='custom-radio-input'/> 

<label for='custom-radio-input'>
  <button>
    <svg/>
  </button>
</label>
```

If ever, the inner element would be a label to the radio, in this custom element example, it's a div: https://github.com/vimeo/iris/blob/main/src/components/inputs/Radio/Radio.examples.story.tsx#L71-L110

2023-05-24 08:26 UTC, nathanbrud commented
@juliewongbandue Thanks got it!

I tried implementing your idea but it will not work because besides style, Button has logic that affect how it looks and the rendering order.

examples
```
  const radius = pill ? 50 : borderRadii[size] + 2;

  const iconOnly = typeof children === 'undefined' && icon;
  const iconLeft = iconPosition === 'left' && icon;
  const iconRight = iconPosition === 'right' && icon;
  const iconFeatured = iconPosition === 'featured' && icon;
  const iconAction = iconPosition === 'action' && icon;
```

Also, it will force us to do something like
```
<Radio element="button" buttonProps={{ format: .... }} />
```
Which is not very and nice and also super complex for ts.

What I came us with is just use it as custom element
```
        <Radio>
          <Button pill format="secondary" icon={<Pencil />}>
            Hello
          </Button>
        </Radio>
```
This trick is here:
```
  const clonedElementProps: {
    disabled: boolean;
    checked: boolean;
    element?: string;
  } = {
    disabled,
    checked,
  };

  if (children.type.displayName === 'Button') {
    clonedElementProps.element = 'span';
  }
```

And added a warning for when this happens so the developer is aware
WDYT?

2023-05-25 15:02 UTC, juliewongbandue commented
Oh I didn't notice this before, but it looks like you _can_ change the button element to a `span` with the `element` prop: https://github.com/vimeo/iris/blob/main/src/components/Button/Button.tsx#L34

🎉

2023-06-12 06:17 UTC, nathanbrud commented
@tylerthegrove can you please review?

2023-06-12 14:44 UTC, Boughtmanatee5 requested changes

2023-06-12 15:54 UTC, nathanbrud commented on src/components/Button/Button.style.ts
> +  ${buttonChecked}
thanks, added

2023-06-12 16:31 UTC, Boughtmanatee5 approved these changes
👍 looks good to me if it looks good to @juliewongbandue!

2023-06-12 17:01 UTC, juliewongbandue approved these changes
lgtm!

2023-06-13 16:28 UTC, merged