Dsys 4 dsys 5 slider updates
vimeo/iris pull request #280
Opened 2023-06-22 09:17 UTC by nathanbrud

https://vimean.atlassian.net/browse/DSYS-4
https://vimean.atlassian.net/browse/DSYS-5

## What this PR does 
* Change the design on Slider component based on the new approved design.
* Added values in onDragEnd callback
* Added unit test

## Screenshots & Recordings 
![image](https://github.com/vimeo/iris/assets/9106375/a4a601bd-181e-4027-bb5e-0368b1c92a95)

## How it does that 
* Move input out from the `Handle` component into the main `Slider` component.
* Remove unused styling.

## Testing 
<img width="482" alt="image" src="https://github.com/vimeo/iris/assets/9106375/28e646af-1018-4e47-88c9-b2d6c0582925">

2023-06-23 06:01 UTC, juliewongbandue requested changes
Just a few questions here. 

It would also be excellent for this input to handle left and right keyboard arrows to adjust the input values.

One more note is to add a role and common aria attributes associated with the slider: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/slider_role.

2023-06-23 06:14 UTC, nathanbrud commented on src/components/inputs/Slider/Slider.tsx
> +  function dispatchChangeEvent(callback) {
In the previous flow we had 2 events being fired: `onDragEnd` and `onChange`
They both were fired with an event but only the `onChange` event had value, which was coming from the `<Hidden />` component.

I combined both of them to have the same flow so both `onChange` and `onDragEnd` will fire an event with value.

2023-06-23 06:15 UTC, nathanbrud commented on src/components/inputs/Slider/Slider.tsx
> +    dispatchChangeEvent(onChange);
dispatchChangeEvent is just a wrapper to call `onChange` or `onDragEnd` because they are now the same so it's to save code duplication.

2023-06-23 06:17 UTC, nathanbrud commented on src/components/inputs/Slider/Slider.tsx
> +      dispatchChangeEvent(onDragEnd);
`onDragEnd` was called before with the mouse up event, which doesn't have a value.
using the same method for `onChange` and for `onDragEnd` will send an event with a value.

2023-06-23 06:22 UTC, nathanbrud commented
@juliewongbandue Thanks so much for reviewing this!
About the keyboard for the input - it's a pretty big change and a new functionality so I want to do it a separate PR.
I'm adding the aria attributes and the role :)

2023-06-25 06:39 UTC, nathanbrud commented
Closing for https://github.com/vimeo/iris/pull/282 (with Iris access now)

2023-06-25 06:39 UTC, closed without merging