add disabled as prop to support visibilty modes of tooltip
vimeo/iris pull request #300
Opened 2023-07-27 12:09 UTC by sbatel

## What this PR does 
this change is needed to prevent situations like this - 
<img width="727" alt="image" src="https://github.com/vimeo/iris/assets/38322603/793a88e8-b4bf-4a27-a0aa-a6d62f4ec670">
we would like to hide the tooltip when the popover is open (the tooltip wraps the button the is wrapped by the popover)

Support the ability to disable/enable tooltip (control visibility).

## Screenshots & Recordings 
<img width="473" alt="image" src="https://github.com/vimeo/iris/assets/38322603/f927e035-d2e9-4470-8d62-4e4090de65f8">

## How it does that 
Added the 'disabled' prop (default value is false) that effects the Tip's style (visibility: visible/hidden)
## Testing

2023-07-27 13:14 UTC, juliewongbandue commented
Hey @sbatel can you add unit tests for this component as well?

2023-07-31 15:29 UTC, juliewongbandue commented on src/components/Tip/Tip.types.ts
> +   * Controlls the tooltip visibility.
Small spelling nit:

```suggestion
   * Controls the tooltip visibility.
```

2023-07-31 20:51 UTC, juliewongbandue requested changes
Just a small nit!

2023-08-01 07:38 UTC, sbatel commented on src/components/Tip/Tip.types.ts
> +   * Controlls the tooltip visibility.
:) fixed!

2023-08-01 14:16 UTC, juliewongbandue approved these changes

2023-08-02 12:56 UTC, merged