Resizable panel
vimeo/iris pull request #35
Opened 2021-08-05 21:12 UTC by kevingraber

2021-08-11 19:31 UTC, seanmcintyre requested changes
More questions/thoughts: 

What is the reasoning behind managing the width externally? A width determined by dragging seems like it would be necessarily always intrinsic.

I think you could simplify the dragging management and cease to rely on binding event listeners by combining `draggable`, `onDragStart`, `onDragEnd`, and `onDrag` on the `<DragEdge />` component if you make it invisible. The `onDrag` event should provide cursor coordinates that you can use to handle the resizing.

Don't forget dark mode support!

I think the animation could use some work. It's kind of janky, some elements flicker, and some animate at very different speeds. This is easier to see if you slow it down in devtools:

https://user-images.githubusercontent.com/319302/129091185-96ef7c12-de1f-4087-915e-192fbf9b90e9.mov

2021-08-11 19:51 UTC, kevingraber commented on src/layout/Panel/Panel.examples.story.tsx
> +        {/* TODO - Panel needs a child - is it ok to use a fragment? */}
I was, but after visiting the `Panel.types.ts` file it went away.

2021-08-12 20:10 UTC, kevingraber commented
I tried using the `draggable` attribute but wasn't able to get a good UX. The dragging was a lot choppier, there were still remnants of the dragging UI (cursor icon), and the drag edge would still be active for a second or two after the drag ended.

2021-08-16 15:22 UTC, kevingraber commented
Thanks for all the feedback @seanmcintyre. I started looking into the panel animation and found the following.

https://user-images.githubusercontent.com/15743757/129586470-10f33168-0db3-4ab4-931c-cd668b37d29d.mov

It looks like if I close the panel from outside, the animation works as expected. If I close it using the button from the inside, the entire panel disappears before it is entirely off the screen. Also if I set focus on an element inside the panel and then close it using the external button, the panel exhibits the same behavior of closing before it's fully off the screen. I don't think this has anything to with any changes I made. Any thoughts on what could be happening here?

Also I believe my builds are failing because of lint issues in files I haven't touched?

2021-08-30 18:50 UTC, kevingraber commented
@seanmcintyre everything looks great to me! Design signed off as well.

2021-09-01 19:14 UTC, seanmcintyre approved these changes

2021-09-01 19:15 UTC, merged